server:
  port: 8090
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    # 发件人邮箱
    username: 1483618794@qq.com
    # QQ邮箱的授权码
    password: igolqpbviwtujcec
    # 使用465端口进行SSL加密
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true  # 如果需要使用STARTTLS支持
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sqlpub.com:3306/yunshu
    username: lichun
    password: PDRILjOGQbYV63ri
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
# 设置日志级别
logging:
  level:
    root: info
